version: '3'
services:
    server:
        image: grpc-server
        build:
            context: .
            dockerfile: ./Dockerfile.server
        volumes:
            - ".:/server"
    client:
        image: grpc-client
        build:
            context: .
            dockerfile: ./Dockerfile.client
        ports: 
            - "4251:5000"
        depends_on:
          - server
        volumes:
            - ".:/client"